apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: codegentest
  janus-idp.io/tekton: codegentest
  backstage.io/kubernetes-id: codegentest
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: codegentest
resources:
  - application-dev.yaml