apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: codegentest
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhdhpai-rolling-demo/codgentest-may7:81b4f79f362c3458bce56f2616493be43ee05088@sha256:eee1d54059dfd49288dd13a1dab6bcb307abff5d030799146731ece457bfeac3 # use pre-built to bootstrap
          name: app-inference
